const BACKEND_BASE_URL="http://localhost:3000"
const USER_MOVIE_RATING_URL=`${BACKEND_BASE_URL}/user/movie/rating`
const USER_RATINGS_URL=`${BACKEND_BASE_URL}/user/ratings`
const USER_RECOMMENDATIONS_URL=`${BACKEND_BASE_URL}/user/recommendations`

export {BACKEND_BASE_URL,USER_MOVIE_RATING_URL,USER_RATINGS_URL,USER_RECOMMENDATIONS_URL}